apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "blur-detection.fullname" . }}
  labels:
    {{- include "blur-detection.labels" . | nindent 4 }}
spec:
  rules:
  - host: blurrr.kube
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "blur-detection.fullname" . }}
            port: 
              number: 80
