variables:
  IMAGE_NAME: ghcr.io/uzziell/blurrr
  IMAGE_TAG: "1.0.0-${CI_PIPELINE_IID}"

stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  script:
    - test -s ./requirements.txt

build_image:
  stage: build
  image: docker:20.10.21
  services:
    - docker:20.10.21-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
