variables:
  IMAGE: "${CI_REGISTRY}/${CI_REGISTRY_USER}/blur-detection-web-app"
  IMAGE_TAG: "${IMAGE}:1.0.0-${CI_PIPELINE_IID}"

stages:
  - test
  - build
  - deploy

check-requirementes-file:
  stage: test
  script:
    - test -s ./requirements.txt

docker-build:
  stage: build
  image: docker:20.10.21
  services:
    - name: docker:20.10.21-dind
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  script:
    - echo "Deploying to k8s $CI_COMMIT_BRANCH"
