variables:
  IMAGE_NAME: ghcr.io/uzziell/blurrr
  IMAGE_TAG: "1.0.0-${CI_PIPELINE_IID}"

stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  script:
    - test -s ./requirements.txt

build_image:
  stage: build
  image: docker:20.10.21
  services:
    - docker:20.10.21-dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context UZziell/blur-detection-web-app:local
    - kubectl apply -f deploy/secrets.yaml