variables:
  IMAGE: "${CI_REGISTRY}/${CI_REGISTRY_USER}/$CI_PROJECT_NAME"
  IMAGE_TAG: "${IMAGE}:1.0.0-${CI_PIPELINE_IID}"
  CS_ANALYZER_IMAGE: registry.gitlab.com/security-products/container-scanning/trivy:5

stages:
  - test
  - build
  - check
  - deploy

check-requirementes-file:
  stage: test
  script:
    - test -s ./requirements.txt

docker-build:
  stage: build
  needs:
    - "check-requirementes-file"
  image: docker:20.10.21
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  services:
    - docker:20.10.21-dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

container-scanning:
  stage: check
  needs:
    - "docker-build"
  image: "$CS_ANALYZER_IMAGE$CS_IMAGE_SUFFIX"
  variables:
    # To provide a `vulnerability-allowlist.yml` file, override the GIT_STRATEGY variable in your
    # `.gitlab-ci.yml` file and set it to `fetch`.
    # For details, see the following links:
    # https://docs.gitlab.com/ee/user/application_security/container_scanning/index.html#overriding-the-container-scanning-template
    # https://docs.gitlab.com/ee/user/application_security/container_scanning/#vulnerability-allowlisting
    GIT_STRATEGY: none
  allow_failure: true
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
      dependency_scanning: gl-dependency-scanning-report.json
    paths:
      [gl-container-scanning-report.json, gl-dependency-scanning-report.json]
  dependencies: []
  script:
    - gtcs scan
  rules:
    - if: $CONTAINER_SCANNING_DISABLED
      when: never

    # Add the job to merge request pipelines if there's an open merge request.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" &&
        $CI_GITLAB_FIPS_MODE == "true" &&
        $CS_ANALYZER_IMAGE !~ /-(fips|ubi)\z/
      variables:
        CS_IMAGE_SUFFIX: -fips
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

    # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never

    # Add the job to branch pipelines.
    - if: $CI_COMMIT_BRANCH &&
        $CI_GITLAB_FIPS_MODE == "true" &&
        $CS_ANALYZER_IMAGE !~ /-(fips|ubi)\z/
      variables:
        CS_IMAGE_SUFFIX: -fips

deploy:
  stage: deploy
  needs:
    - container-scanning
  script:
    - echo "Deploying to k8s $CI_COMMIT_BRANCH"
